version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run Maven tests
          command: mvn clean test
      - run:
          name: Generate coverage report
          command: mvn jacoco:report
      - run:
          name: Generate Checkstyle report
          command: mvn checkstyle:checkstyle
      - run:
          name: Upload Checkstyle report as an artifact
          command: mv target/checkstyle-report.txt target/checkstyle-report.txt
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
