version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run Maven tests
          command: mvn clean test
      - run:
          name: Generate coverage report
          command: mvn jacoco:report
      - run:
          name: Generate Checkstyle report
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-report
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p output
            mv target/site/apidocs/* output/
            git clone --branch gh-pages https://$hamza098@github.com/HamzaLATRACH8/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            rm -rf *
            mv ../output/* .
            git add .
            git commit -m "Update Javadoc"
            git push https://$hamza098@github.com/HamzaLATRACH8/ceri-m1-techniques-de-test.git gh-pages
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)




workflows:
  build-and-test:
    jobs:
      - test-java
      - generate-docs