version: 2.1
jobs:
  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run Maven tests
          command: mvn clean test
      - run:
          name: Generate coverage report
          command: mvn jacoco:report
      - run:
          name: Generate Checkstyle report
          command: mvn checkstyle:checkstyle
      - store_artifacts:
          path: target/checkstyle-result.xml
          destination: checkstyle-report
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
            - persist_to_workspace:
                root: .
                paths:
                  - target/site/apidocs

      - run:
          name: Configure Git for GitHub Pages
          command: |
            git config --global user.email "your-email@example.com"
            git config --global user.name "Your Name"
            - run:
                name: Create gh-pages Branch If Not Exists
                command: |
                  git fetch origin
                  if ! git rev-parse --verify origin/gh-pages; then
                    git checkout --orphan gh-pages
                    git rm -rf .
                    echo "Placeholder for GitHub Pages" > index.html
                    git add index.html
                    git commit -m "Initial commit for GitHub Pages"
                   git push https://$GITHUB_TOKEN@github.com/MejaiWajdi/ceri-m1-techniques-de-test.git gh-pages
                  fi
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            mkdir -p output
            mv target/site/apidocs/* output/
            git clone --branch gh-pages https://$hamza098@github.com/HamzaLATRACH8/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            rm -rf *
            mv ../output/* .
            git add .
            git commit -m "Update Javadoc"
            git push https://$hamza098@github.com/HamzaLATRACH8/ceri-m1-techniques-de-test.git gh-pages
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash)




workflows:
  build-and-test:
    jobs:
      - test-java
      - generate-docs